import Head from "next/head";

const Header = () => {
    return (
        <Head>
            <title>Global Talk</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />

            <link rel="preconnect" href="https://fonts.googleapis.com" />

            <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin="true"
            />
            <link
                href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Kanit:ital@0;1&family=Montserrat:wght@400;600;700&display=swap"
                rel="stylesheet"
            />
        </Head>
    );
};

export default Header;
