import Head from "next/head";

const Header = () => {
    return (
        <Head>
            <title>Global Talk</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
            <style>
                @import
                url("https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Kanit:ital@0;1&family=Montserrat:wght@400;600;700&display=swap");
            </style>
        </Head>
    );
};

export default Header;
